### ISSUE TITLE
forcing version of requests

### ISSUE THREAD

**Issue by kostyrev** [Nosmoht/python-foreman#19]
Hello!
Is it really necessary to force version of requests?
As of now this class requires

```
requests==2.5.3
```

and forces the installation of 2.5.3

but on my default CentOS7 box

```
pip show requests

---
Metadata-Version: 1.1
Name: requests
Version: 2.6.0
```

would it be enough to change [requirements.txt](https://github.com/Nosmoht/python-foreman/blob/master/requirements.txt#L1) to

```
requests>=2.5.3
```

**Comment by Nosmoht** [comment]
Totally right. Let's change it.

**Comment by Nosmoht** [comment]
Fixed with https://github.com/Nosmoht/python-foreman/commit/2eed06414acc8af3bec3993d9a12ea4a04e2fdc3
