### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by stintel** [Nosmoht/python-foreman#20]
Would you mind releasing a new version of this module, and also update that version in setup.py? Thanks!

**Comment by Nosmoht** [comment]
Sure.

**Comment by Nosmoht** [comment]
Fixed with https://github.com/Nosmoht/python-foreman/commit/37abffdf3dc6e87a3c65d4436f6e4b8692706bcb

**Comment by stintel** [comment]
@Nosmoht thanks!
