### ISSUE TITLE
interface attributes in host creation

### ISSUE THREAD

**Issue by mathiear** [Nosmoht/python-foreman#23]
Hello,

Am I correct saying there is no way to create a host adding interfaces_attributes in the same way we can add volumes_attributes ?

I'm trying to create a host with the following data:

```
data = { 'name': host_name,
        'ip': host_ip,
        'environment_id': host_env_id,
        "ptable_name": default_partition_table,
        'architecture_id': default_architecture_id,
        'medium_id': default_medium_id,
        'domain_id': 2,
        'operatingsystem_id': operatingsystem_id,
        'compute_resource_id': compute_resource_id,
        'compute_profile_id': '5',
        'hostgroup_id': '1',
                'compute_attributes': {
                    'cpus': host_cpu,
                    'memory_mb': host_ram,
                    'path': host_folder,
                    'volumes_attributes': {
                        '0': {
                            'name': 'Hard disk',
                            'datastore': host_datastore,
                            'size_gb': host_disk
                        }
                    },
                    'interfaces_attributes': {
                        '0': {
                            'compute_type': "VirtualE1000",
                            'compute_network': 'VM Network'
                        }
                    },
                },
        'build': 'true' }
```

**Comment by Nosmoht** [comment]
Hi @mathiear,

it should be possible as the data dict is passed without modification to the API. See https://github.com/Nosmoht/python-foreman/blob/master/foreman/foreman.py#L538.

Do you get any error?

**Comment by mathiear** [comment]
Hi,
thanks for the reply.
There is no error in the foreman log, the interfaces_attributes I add are simply not in the body of the POST request:

Processing by Api::V2::HostsController#create as JSON
Parameters: [additional interfaces are present] [...]
Rendered api/v2/hosts/create.json.rabl (93.6ms)
Body: [additional interfaces are NOT present] [...]
Completed 201 Created in 5389ms (Views: 90.4ms | ActiveRecord: 34.3ms)

**Comment by Nosmoht** [comment]
Found in Foreman API docu.

```
host[interfaces_attributes]
optional , nil allowed  
Host’s network interfaces.

Value: Must be an Array of nested elements
```

```
host[compute_attributes]
optional , nil allowed  
Additional compute resource specific attributes.

Value: Must be Hash
```

So, according to the docu interface attributes must be an array, not a hash like with compute_attributes :wink:

**Comment by mathiear** [comment]
hehe, read the manual...

it indeed did the trick :

```
            'interfaces_attributes': [
                {
                    'type': 'interface',
                    'ip': host_ip,
                    "subnet_id": 1,
                    "primary": True,
                    "provision": True,
                    "managed": True,
                    'compute_attributes': {
                        'type': "VirtualVmxnet3",
                        'network': compute_network
                    }
                }
            ],
```

one other thing which made my life harder: the compute_attributes are not like the hammer cli which uses compute_type and compute_network.

Anyway, thanks a lot for your help! :)
